# Generated by Django 3.0.5 on 2020-12-15 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0002_sqlite'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SQLite',
            new_name='Posts',
        ),
    ]
