# Generated by Django 3.0.5 on 2020-12-15 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0003_auto_20201215_1158'),
    ]

    operations = [
        migrations.CreateModel(
            name='Selec',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
